import os
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import gravis

# Download NLTK resources (if not already downloaded)
# nltk.download('punkt')
# nltk.download('stopwords')

# Function to extract words related to health and fitness
def extract_health_words(text):
    # Tokenize the text into words
    words = word_tokenize(text)
    
    # Remove stopwords and punctuation
    stop_words = set(stopwords.words('english'))
    words = [word.lower() for word in words if word.isalpha() and word.lower() not in stop_words]
    
    # Define health-related keywords
    health_keywords= [
    "health",
    "wellness",
    "fitness",
    "nutrition",
    "exercise",
    "diet",
    "healthy",
    "well-being",
    "physical",
    "mental health",
    "medical",
    "lifestyle",
    "wellness",
    "medicine",
    "wellness",
    "self-care",
    "prevention",
    "hygiene",
    "immune",
    "nutrition",
    "nutritionist",
    "dietitian",
    "vaccine",
    "doctor",
    "physician",
    "nurse",
    "hospital",
    "clinic",
    "pharmacy",
    "therapy",
    "treatment",
    "recovery",
    "patient",
    "symptom",
    "diagnosis",
    "condition",
    "illness",
    "disease",
    "healthcare",
    "wellness",
    "fitness",
    "medical",
    "screening",
    "checkup",
    "healthful",
    "healthier",
    "mindfulness",
    "relaxation",
    "stress management",
    "sleep",
    "rest",
    "resilience",
    "strength",
    "endurance",
    "flexibility",
    "vitality",
    "energy",
    "longevity",
    "holistic",
    "organic",
    "natural",
    "herbal",
    "supplement",
    "vitamin",
    "mineral",
    "nutrient",
    "calorie",
    "hydration",
    "water",
    "exercise",
    "workout",
    "training",
    "cardio",
    "aerobic",
    "anaerobic",
    "strength training",
    "yoga",
    "pilates",
    "meditation",
    "breathing",
    "mind-body",
    "fitness",
    "gym",
    "physical therapy",
    "rehabilitation",
    "mobility",
    "flexibility",
    "posture",
    "ergonomics",
    "workplace wellness",
    "ergonomics",
    "disability",
    "chronic",
    "acute",
    "injury",
    "recovery",
    "pain management",
    "rehabilitation",
    "assistive devices",
    "mobility aids",
    "prosthetic",
    "orthotic",
    "adaptive equipment",
    "inclusive",
    "accessibility",
    "mental health",
    "psychology",
    "counseling",
    "therapy",
    "psychotherapy",
    "cognitive-behavioral",
    "mindfulness",
    "meditation",
    "stress management",
    "resilience",
    "emotional well-being",
    "mental illness",
    "depression",
    "anxiety",
    "bipolar",
    "schizophrenia",
    "obsessive-compulsive",
    "trauma",
    "PTSD",
    "addiction",
    "substance abuse",
    "recovery",
    "rehabilitation",
    "support group",
    "peer support",
    "family therapy",
    "group therapy",
    "crisis intervention",
    "suicide prevention",
    "mental health awareness",
    "stigma",
    "discrimination",
    "self-care",
    "self-compassion",
    "self-esteem",
    "self-awareness",
    "self-improvement",
    "self-help",
    "mindfulness",
    "meditation",
    "journaling",
    "exercise",
    "nutrition",
    "sleep",
    "social support",
    "community",
    "relationships",
    "communication",
    "boundaries",
    "resilience",
    "stress management",
    "coping skills",
    "relaxation techniques",
    "positive psychology",
    "gratitude",
    "optimism",
    "happiness",
    "joy",
    "fulfillment",
    "purpose",
    "meaning",
    "life satisfaction",
    "quality of life",
    "mental health advocacy",
    "policy",
    "awareness",
    "education",
    "outreach",
    "recovery",
    "peer support",
    "stigma reduction",
    "community resources",
    "accessibility",
    "equity",
    "mental health services",
    "counseling",
    "therapy",
    "medication",
    "psychiatric",
    "hospitalization",
    "outpatient",
    "inpatient",
    "residential",
    "partial hospitalization",
    "intensive outpatient",
    "day program",
    "supportive housing",
    "crisis intervention",
    "hotline",
    "emergency services",
    "telehealth",
    "online therapy",
    "self-help resources",
    "support groups",
    "peer support",
    "advocacy organizations",
    "mental health awareness campaigns",
    "mental health first aid",
    "crisis intervention training",
    "suicide prevention training",
    "psychological first aid",
    "trauma-informed care",
    "resilience training",
    "stress management programs",
    "mindfulness workshops",
    "mental health screenings",
    "counseling services",
    "therapy sessions",
    "medication management",
    "psychiatric evaluation",
    "crisis intervention",
    "emergency psychiatric services",
    "hospitalization",
    "residential treatment",
    "partial hospitalization programs",
    "intensive outpatient programs",
    "outpatient services",
    "community mental health centers",
    "mental health clinics",
    "psychiatric hospitals",
    "rehabilitation centers",
    "long-term care facilities",
    "supportive housing",
    "crisis hotlines",
    "suicide prevention lifelines",
    "online support groups",
    "peer support programs",
    "advocacy organizations",
    "mental health awareness campaigns",
    "public health initiatives",
    "policy advocacy",
    "research funding",
    "mental health education",
    "training programs",
    "mental health parity laws",
    "insurance coverage",
    "accessibility",
    "equity",
    "stigma reduction",
    "social inclusion",
    "mental health screening",
    "early intervention",
    "prevention programs",
    "risk assessment",
    "protective factors",
    "mental health promotion",
    "resilience building",
    "positive psychology",
    "self-care practices",
    "mindfulness techniques",
    "stress management strategies",
    "healthy coping skills",
    "social support networks",
    "community engagement",
    "advocacy efforts",
    "policy change",
    "awareness campaigns",
    "education initiatives",
    "research advancements",
    "treatment innovations",
    "mental health services delivery",
    "integrated care models",
    "telemedicine",
    "digital health solutions",
    "evidence-based practices",
    "culturally competent care",
    "trauma-informed approaches",
    "recovery-oriented systems",
    "person-centered care",
    "shared decision-making",
    "peer support services",
    "family involvement",
    "collaborative care teams",
    "case management",
    "care coordination",
    "continuity of care",
    "quality improvement",
   
]
    
    # Extract words related to health and fitness
    health_words = [word for word in words if word in health_keywords]
    
    return health_words

# Function to read text files and extract health-related words
def process_files_in_directory(directory):
    health_words = []
    # Iterate over files in the directory
    for filename in os.listdir(directory):
        if filename.endswith(".txt"):  # Assuming text files have .txt extension
            file_path = os.path.join(directory, filename)
            with open(file_path, 'r', encoding='utf-8') as file:
                text = file.read()
                # Extract health-related words from the text
                extracted_words = extract_health_words(text)
                # Add extracted words to the list
                health_words.extend(extracted_words)
    return health_words

# Directory containing the text files
data_directory = "H:/Coding/Semester 6/Graph Theory/Processed Data/Health and Fitness/page_1.txt"

# Process files in the directory and extract health-related words
health_words = process_files_in_directory(data_directory)

# Create a graph
G = gravis.Graph()

# Add nodes (words)
for word in set(health_words):
    G.add_node(word)

# Display the graph
gravis.plot(G)
